### ISSUE TITLE
Bug: Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry.

### ISSUE THREAD

**Issue by mihaisavezi** [vaadin/vaadin-lumo-styles#105]
I use this package indirectly via `@vaadin/vaadin-grid`. Now imagine the usecase that an app which uses `vaadin-grid` needs to load a different app which uses `vaadin-grid`. The bundles are not shared, and so both apps will call:

```javascript
customElements.define('vaadin-lumo-styles', Lumo);
```

One of them will throw an error. This could be easily solved in the package
```javascript
customElements.get('vaadin-lumo-styles') || customElements.define('vaadin-lumo-styles', Lumo);
```

**Comment by web-padawan** [comment]
Thank you for the issue. This is a known limitation of web components: you can't register the same component twice.
So, if the bundles are not shared, you will face this problem. 

Updating `customElements.define` here won't help if you have two versions of the grid in your page. There will be still an error thrown because we use Polymer and it defines some elements like `dom-module`.

One potential solution could be using webpack module federation to share code between different apps.

I'm closing this issue because there is nothing we can do at the moment to support this use case.

**Comment by mihaisavezi** [comment]
I made a temporary workaround if anyone might need it.

```javascript
function safeDecorator(fn) {
  // eslint-disable-next-line func-names
  return function(...args) {
    try {
      return fn.apply(this, args);
    } catch (error) {
      if (
        error instanceof DOMException &&
        error.message.includes('has already been used with this registry')
      ) {
        return false;
      }
      throw error;
    }
  };
}

customElements.define = safeDecorator(customElements.define);
```
