### ISSUE TITLE
Use without lumo

### ISSUE THREAD

**Issue by ebatgerel** [vaadin/vaadin-lumo-styles#18]
Can i use it without lumo theme ? if can how to remove lumo style from project ?

**Comment by web-padawan** [comment]
You can use the components without the Lumo theme, if you mean that. In order to achieve that, you need to import component from the `src` folder like this:

```
<link rel="import" href="bower_components/vaadin-combo-box/src/vaadin-combo-box.html">
```

You will have to implement your own theme, though, since the unstyled components currently only have a minimum of CSS which is not intended to cover all the possible states out of the box.
