### ISSUE TITLE
Export styles in a way that can be easily consumed in LitElement based views/components

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-lumo-styles#90]
There should be an easy and clean way to import Lumo styles into LitElement based components and views.

There may be different ways of achieving this. One idea would be to make the Lumo JS files (in P3/npm version) explicitly export CSSResult objects (adding a dependency to `lit-element`) like:

```js
export default css`
  ...
`;
```

Another alternative might be to provide the CSS sources as `*.css` files which could be additionally included in npm and used in a variety of ways (e.g. webpack loader configuration can import CSS file directly as a CSSResult). In this case it might make sense to add a build step to generate the current HTML import files and JS modules using the CSS files as the source for avoiding CSS duplication.

It should be considered if this needs to be done in a backwards compatible way keeping the current P2 sources, or can we convert the repository to next gen and release as a new major?

This is needed for https://github.com/vaadin-learning-center/crm-tutorial-typescript/issues/18

Somewhat related: #69, #81

**Comment by Haprog** [comment]
And the same should probably be done for https://github.com/vaadin/vaadin-material-styles/ too.

**Comment by web-padawan** [comment]
Note, this was also requested at https://github.com/vaadin/vaadin-themable-mixin/issues/73#issuecomment-562149495

**Comment by jouni** [comment]
What would be the reasons to do this in a backwards compatible way? The only reason that comes to mind at the moment is to avoid having to make fixes in two versions. But it feels unnecessary overhead.

I would go ahead with a new major version, iterate faster towards the next LTS version. I’m not expecting us to backport any bigger changes to the current LTS version.

**Comment by rolfsmeds** [comment]
The upcoming theming mechanism (see acceptance criteria in https://github.com/vaadin/platform/issues/1571) would actually need to have Lumo stylesheets like typography, badges etc as plain .css files, so that they can be imported from the npm dependency using the feature described as _"Css can be imported to the theme from npm dependencies via definitions in the theme folder."_

The idea there is that you define stylesheets to import from npm dependencies in a json file like so:
```
{
  "importCss": ["@foo/bar.css"]
}
```
which automatically loads it as a global stylesheet.

**Comment by web-padawan** [comment]
@rolfsmeds thanks for letting me know, I wasn't aware of that requirement.

The issue is about making style modules work with LitElement components and they use `css` tagged literals.
This is that our components users from the Polymer Project community would expect.

I created a separate feature requests for plan .css files: https://github.com/vaadin/vaadin-lumo-styles/issues/97

We can still have those and then also have a gulp task that creates `.html` files based on them.
